
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author santiagoandre
 */
public class parcial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(parcial.class.getName());

    /**
     * Creates new form parcial
     */
    public parcial() {
        initComponents();
        String password = JOptionPane.showInputDialog(
        "Ingrese la contraseña:");
        if (password.equals("1234")) {

            JOptionPane.showMessageDialog(null,
                    "Bienvenido");

        } else {

            JOptionPane.showMessageDialog(null,
                    "Contraseña incorrecta");

            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlblcliente = new javax.swing.JLabel();
        jlbltipo = new javax.swing.JLabel();
        jlblcompra = new javax.swing.JLabel();
        jlbltotal = new javax.swing.JLabel();
        jtxtcliente = new javax.swing.JTextField();
        jtxtTipo = new javax.swing.JTextField();
        jtxtmonto = new javax.swing.JTextField();
        jtxtResultado = new javax.swing.JTextField();
        jbtnCalcular = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("KoHo", 3, 14)); // NOI18N
        jLabel1.setText("=====Calculadora de clientes=====");

        jlblcliente.setBackground(new java.awt.Color(255, 51, 0));
        jlblcliente.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jlblcliente.setText("Cliente:");

        jlbltipo.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jlbltipo.setText("Tipo de cliente:");

        jlblcompra.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jlblcompra.setText("Compra total:");

        jlbltotal.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jlbltotal.setText("Total al pagar:");

        jtxtcliente.addActionListener(this::jtxtclienteActionPerformed);

        jtxtTipo.addActionListener(this::jtxtTipoActionPerformed);

        jtxtResultado.setText(" ");
        jtxtResultado.setEnabled(false);

        jbtnCalcular.setText("Calcular");
        jbtnCalcular.addActionListener(this::jbtnCalcularActionPerformed);

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(this::jbtnLimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlbltotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnLimpiar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlblcompra)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnCalcular))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbltipo)
                                    .addComponent(jlblcliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblcliente)
                    .addComponent(jtxtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbltipo)
                    .addComponent(jtxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblcompra)
                    .addComponent(jtxtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbltotal)
                    .addComponent(jtxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCalcular)
                    .addComponent(jbtnLimpiar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTipoActionPerformed

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed

String textoMonto = jtxtmonto.getText();
String tipo = jtxtTipo.getText();


if (textoMonto.isEmpty() || tipo.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Todos los campos son obligatorios");
} else {
    // Convertir el texto a número
    double monto = Double.parseDouble(textoMonto);
    double descuento = 0;
    double totalPagar = 0;

    if (tipo.equalsIgnoreCase("estudiante")) {
        descuento = monto * 0.10;
    } else if (tipo.equalsIgnoreCase("docente")) {
        descuento = monto * 0.20;
    } else if (tipo.equalsIgnoreCase("invitado")) {
        descuento = 0;
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Tipo de cliente no válido");
    }


    totalPagar = monto - descuento;
    

    jtxtResultado.setText(String.valueOf(totalPagar));
    

    javax.swing.JOptionPane.showMessageDialog(this, "Cálculo realizado con éxito");
}
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    private void jtxtclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtclienteActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        // 1. Limpiar todos los JTextField (ponemos el texto en blanco "")
jtxtcliente.setText("");
jtxtTipo.setText("");
jtxtmonto.setText("");
jtxtResultado.setText("");

// 2. Colocar el cursor nuevamente en el primer campo (Validación de flujo)
jtxtcliente.requestFocus();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new parcial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JLabel jlblcliente;
    private javax.swing.JLabel jlblcompra;
    private javax.swing.JLabel jlbltipo;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JTextField jtxtResultado;
    private javax.swing.JTextField jtxtTipo;
    private javax.swing.JTextField jtxtcliente;
    private javax.swing.JTextField jtxtmonto;
    // End of variables declaration//GEN-END:variables
}
